spring.application.name=EventManager

# Server Port
server.port=8080

# PostgreSQL Database Connection
spring.datasource.url=jdbc:postgresql://localhost:5432/club_management
spring.datasource.username=postgres
spring.datasource.password=Girish@9701

# Hibernate Setup (Updates tables automatically based on your Java code)
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect

# JWT Secret (Developer 1 will need this later)
# (This is a random 256-bit key encoded in Base64)
jwt.secret=4qhq8L6lQ2Q8wQ2X7Y9V4X6b8N9Z2C4h6q8L6lQ2Q8w=
jwt.expiration=86400000